max_tweets: 500
search_query: 'covid'
hashtag: '#coronavirus'
from: 'CNN'
since: '2022-01-01'
until: '2022-01-15'
country: 'USA'
radius: '100km'
language: 'en'
sentiment: True
output_file: 'tweets.csv'
attributes:
  - date
  - content
  - username
  - hashtags
  - retweets
  - likes
  - sentiment
