max_tweets: 100
search_query: 'covid'
#hashtag: '#coronavirus'
#from: 'CNN'
since: '2020-01-01'
until: '2022-01-15'
#country: 'USA'
#radius: '100km'
language: 'en'
sentiment: True
output_file: 'tweets.csv'
attributes:
  - date
  - id
  - content
  - username
#  - hashtags
  - retweets
  - likes
  - language
  - sentiment
  - sentiment category
